language: python
install:
- npm install -g jshint
script:
- jshint includes/ --verbose
- jshint wayf/ --verbose
after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    case "$TRAVIS_BRANCH" in
      "main")
        export GCS_BUCKET_NAME="canvas-static";
        ;;
      "develop")
        export GCS_BUCKET_NAME="canvas-static-test";
        ;;
    esac
  fi
deploy:
  provider: gcs
  edge: true
  access_key_id: GOOG1EO53IDLR56R2KHHN47MLGFNVEC2VGJY5JKTYLLFAX3LXETJQMLYFX4FQ
  secret_access_key:
    secure: "lhy/o01UCN4qp7cX7jEuSj5VXzNSDOZoJ7InB+in1w/A3htTBgirNcuGmctkkjcQ85dQTCm1NXwZSCkSAFhMKuhwYChskyDuYl2ihzr3itdC4H8RnYOh8CZfdNF+8Kax4JXypJ78LEpEVVYu9ABsdxP48nNyu5MfvEywpXWxxV/99JQ9rWk7oivoz95GWKorwnbLIHlv4UIOVcifeFo9LIxMaklHWRZLjlBjPsBQF9R6zSdfCRMMs4EbcQ9bg0kLfDsvCSI/vLBqjEr+qE9lKVIxEbP8epumXRz6Qj59GXW6xuGo6ggmszC0DMaAZmzsAQzzUaGsWsJZZtUn9bpZxKxr+cvLcxHSNP8mYzADKYDHhVKXTP6WsFbMb8CV0WXcZnbqZ4DBzZ+4jstZqf9b+zlVLz3Vix7Lz/lMIcztyFmslxkgO3IAnjw0QTlsg4TReZXY3LXRLj04FFmEwItaE2yBnZG9vn2m4OHxHbUNCXz3BJm7/WRAjDIlQq7e4maHyb9AgkjkfCwni/btwN61F4hyB2I2FYJ54xZ21i4zppv46A7x3QxtwYm3g4lLqQHAc5ag2kIFKWa+6IpUgUnbqOPEa/jU6JqquOZ1i9RW3b3TsnetaR9oLr+FobILU5ZUzrtGTGZLVGk5D104guGRJZ+Sw2kMo/zvg73oUswWQp8="
  bucket: $GCS_BUCKET_NAME
  acl: public-read
  dot_match: false
  local_dir: includes
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(main|develop)$
